# Playtron OS Taskfile
# https://taskfile.dev

version: "3"

tasks:
  rpm-repo:
    desc: Build a local rpm-ostree repository with local RPMs.
    dir: rpm-ostree
    cmds:
      - mkdir -p /tmp/repo || true
      - echo "Checking if any RPMs exist in the /tmp/repo/ directory..."
      - ls /tmp/repo | grep rpm || exit 1
      - createrepo /tmp/repo
      - grep "  - local" playtron-os.yaml || sed -i s'/repos:/repos:\n  - local'/g playtron-os.yaml
      - echo -e "[local]\nname=local\nbaseurl=file:///tmp/repo\nenabled=1\nrepo_gpgcheck=0\ngpgcheck=0" > local.repo

  container-image:
    desc: Build the OCI container image.
    dir: rpm-ostree
    cmds:
      - podman build . --tag playtronos:latest --pull --no-cache

  disk-image:
    desc: Build the OS image from a container hosted in a registry.
    dir: kickstart
    env:
      REGISTRY:
      REGISTRY_TOKEN:
      PROJECT:
      TAG: latest
    preconditions:
      - sh: test "$EUID" == 0
        msg: "This task must be run as root"
      - sh: test -n "$REGISTRY"
        msg: "A value for REGISTRY must be provided"
      - sh: test -n "$REGISTRY_TOKEN"
        msg: "A value for REGISTRY_TOKEN must be provided"
      - sh: test -n "$PROJECT"
        msg: "A value for PROJECT must be provided"
    cmds:
      - cat playtron-os_kickstart.cfg.template | envsubst '${REGISTRY} ${REGISTRY_TOKEN} ${PROJECT} ${TAG}' > playtron-os_kickstart.cfg
      - ./virt-install.sh
      - mv /var/lib/libvirt/images/playtron-os.img "/var/lib/libvirt/images/playtron-os.img_$(date -Iseconds)"
      - virsh undefine --nvram playtron-os

  repo:update:
    desc: "Update the package repository"
    cmds:
      - rm -rf /tmp/repo
      - mkdir -p /tmp/repo
      - aws s3 cp s3://playtron-dev-global-os-public/repos/playtron-app/x86_64/ /tmp/repo/ --recursive
      - read -p "Copy new packages into /tmp/repo and press ENTER to continue"
      - createrepo /tmp/repo
      - aws s3 sync /tmp/repo/ s3://playtron-dev-global-os-public/repos/playtron-app/x86_64/
