#!/bin/bash

if [ $EUID -ne 0 ]; then
	echo "$(basename "$0") must be run as root"
	exit 1
fi


function disable_install_mode {
	rm -rf etc/environment.d
	rm -f etc/systemd/system/resize-root-file-system.service
}

OS_NAME="Playtron GameOS"
RAW_DISK_SIZE=20G
SOURCE_DISK=$1
TARGET_DISK=$2

umount ${TARGET_DISK}*

pv ${SOURCE_DISK} --output ${TARGET_DISK} --size ${RAW_DISK_SIZE} --stop-at-size --numeric 2>&1

if [ "$?" != "0" ]; then
    exit 1
fi

# ensure progress is at 100%
echo "100"

EFI_PART=1
BOOT_PART=2
ROOT_PART=3

if [ "$(uname -m)" == "x86_64" ]; then
	EFI_PART=2
	BOOT_PART=3
	ROOT_PART=4
fi

# update root filesystem
mkdir -p /tmp/playtron-install-target-root
mount  ${TARGET_DISK}*${ROOT_PART} /tmp/playtron-install-target-root
pushd /tmp/playtron-install-target-root/root/ostree/deploy/default/deploy/*.0

disable_install_mode

popd
sync
umount ${TARGET_DISK}*${ROOT_PART}

efibootmgr --delete-bootnum --label "${OS_NAME}" || true
efibootmgr --create --disk ${TARGET_DISK} --part ${EFI_PART} --loader \\EFI\\fedora\\shim.efi --label "${OS_NAME}"
