#!/bin/bash

if [ $EUID -ne 0 ]; then
	echo "$(basename "$0") must be run as root"
	exit 1
fi

set -x
set -e


function disable_install_mode {
	truncate -s 0 etc/machine-id
	rm -rf etc/environment.d
	rm -f etc/systemd/system/var-log.mount
	rm -f etc/systemd/system/var-lib.mount
	rm -f etc/systemd/system/resize-root-file-system.service
	rm -f etc/udev/rules.d/99-media-automount.rules
	rm -f etc/modprobe.d/playtron-installer.conf
}

function get_uuid {
	blkid $1 | grep -oP ' UUID="[^"]*"' | sed 's/ UUID="\(.*\)"/\1/'
}

OS_NAME="Playtron GameOS"
RAW_DISK_SIZE=20G
SOURCE_DISK=$1
TARGET_DISK=$2

umount ${TARGET_DISK}* || true

pv ${SOURCE_DISK} --rate-limit ${CLONE_RATE_LIMIT:-300M} --output ${TARGET_DISK} --size ${RAW_DISK_SIZE} --stop-at-size --numeric 2>&1

if [ "$?" != "0" ]; then
    exit 1
fi

# ensure progress is at 100%
echo "100"

EFI_PART=1
BOOT_PART=2
ROOT_PART=3

if [ "$(uname -m)" == "x86_64" ]; then
	EFI_PART=2
	BOOT_PART=3
	ROOT_PART=4
fi

# regenerate partition UUIDs
rand_uuid=$(uuidgen)
sfdisk --part-uuid ${TARGET_DISK} ${EFI_PART} ${rand_uuid}

rand_uuid=$(uuidgen)
sfdisk --part-uuid ${TARGET_DISK} ${BOOT_PART} ${rand_uuid}

rand_uuid=$(uuidgen)
sfdisk --part-uuid ${TARGET_DISK} ${ROOT_PART} ${rand_uuid}

# get current filesystem UUIDs
old_efi_uuid=$(get_uuid ${TARGET_DISK}*${EFI_PART})
old_boot_uuid=$(get_uuid ${TARGET_DISK}*${BOOT_PART})
old_root_uuid=$(get_uuid ${TARGET_DISK}*${ROOT_PART})

# regenerate filesystem UUIDs
fatlabel --volume-id --reset ${TARGET_DISK}*${EFI_PART}
tune2fs -U random ${TARGET_DISK}*${BOOT_PART}
tune2fs -U random ${TARGET_DISK}*${ROOT_PART}

# get new filesystem UUIDs
new_efi_uuid=$(get_uuid ${TARGET_DISK}*${EFI_PART})
new_boot_uuid=$(get_uuid ${TARGET_DISK}*${BOOT_PART})
new_root_uuid=$(get_uuid ${TARGET_DISK}*${ROOT_PART})


# update efi filesystem
mkdir -p /tmp/playtron-install-target-efi
mount  ${TARGET_DISK}*${EFI_PART} /tmp/playtron-install-target-efi
pushd  /tmp/playtron-install-target-efi

# update UUID references
sed -i -e "s/${old_boot_uuid}/${new_boot_uuid}/" EFI/fedora/bootuuid.cfg

popd
sync
umount ${TARGET_DISK}*${EFI_PART}


# update boot filesystem
mkdir -p /tmp/playtron-install-target-boot
mount  ${TARGET_DISK}*${BOOT_PART} /tmp/playtron-install-target-boot
pushd  /tmp/playtron-install-target-boot

# update UUID references
sed -i -e "s/${old_boot_uuid}/${new_boot_uuid}/" grub2/bootuuid.cfg
sed -i -e "s/${old_boot_uuid}/${new_boot_uuid}/" loader.1/entries/ostree-1.conf
sed -i -e "s/${old_root_uuid}/${new_root_uuid}/" loader.1/entries/ostree-1.conf

popd
sync
umount ${TARGET_DISK}*${BOOT_PART}


# update root filesystem
mkdir -p /tmp/playtron-install-target-root
mount  ${TARGET_DISK}*${ROOT_PART} /tmp/playtron-install-target-root
pushd /tmp/playtron-install-target-root/ostree/deploy/default/deploy/*.0

disable_install_mode

# update UUID references
sed -i -e "s/${old_boot_uuid}/${new_boot_uuid}/" etc/fstab
sed -i -e "s/${old_efi_uuid}/${new_efi_uuid}/" etc/systemd/system/boot-efi.mount
sed -i -e "s/${old_root_uuid}/${new_root_uuid}/" etc/systemd/system/-.mount
sed -i -e "s/${old_boot_uuid}/${new_boot_uuid}/" etc/systemd/system/boot.mount

popd
sync
umount ${TARGET_DISK}*${ROOT_PART}

efibootmgr --delete-bootnum --label "${OS_NAME}" || true
efibootmgr --create --index 0 --disk ${TARGET_DISK} --part ${EFI_PART} --loader \\EFI\\fedora\\shim.efi --label "${OS_NAME}"
