#!/bin/bash

set -x

BAD_LOCALE_INDEX=$(mktemp)
trap 'rm -f "${BAD_LOCALE_INDEX}"' EXIT

for path in boot etc opt usr; do
    find "/${path}" -type f -exec file --mime {} \; 2> /dev/null | grep -v -P "charset=(binary|us-ascii|utf-8|utf-16le)" >> "${BAD_LOCALE_INDEX}"
done

if grep -q "charset" "${BAD_LOCALE_INDEX}"; then
    grep "charset" "${BAD_LOCALE_INDEX}" | cut -d: -f1 |
    while IFS= read -r path_to_rm
        do rm -f -v -- "${path_to_rm}"
    done
fi
