name: Build container image
env:
  REGISTRY: ${{ secrets.REGISTRY }}
  REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
  PROJECT: ${{ secrets.PROJECT }}
  TAG: ${{ github.event.inputs.tag || github.ref_name }}

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version tag'
        required: true

jobs:
  container-image:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
            swap-size-mb: 2048
            remove-dotnet: 'true'
            remove-android: 'true'
            remove-haskell: 'true'
            remove-codeql: 'true'
            remove-docker-images: 'true'
            build-mount-path: '/home/runner'
      - name: Check disks
        run: df -h
      - name: Test container download
        run: podman pull docker.io/library/python
      - name: Check disks 2
        run: df -h
      - uses: actions/checkout@v4
      - name: apt update
        run: sudo apt update
      - name: Install podman
        run: sudo apt --yes install podman
      - name: Install go-task
        run: |
          curl -L -O https://github.com/go-task/task/releases/download/v3.37.2/task_linux_amd64.deb
          sudo dpkg --install task_linux_amd64.deb
          rm --force task_linux_amd64.deb
      - name: Build container image
        run: task container-image:build
      - name: Authenticate to container registry
        run: task container-image:auth
      - name: Upload container image
        run: task container-image:push
