name: Build container image
env:
  REGISTRY: ${{ secrets.REGISTRY }}
  REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
  PROJECT: ${{ secrets.PROJECT }}
  TAG: ${{ github.event.inputs.tag || github.ref_name }}
  TMPDIR: /home/runner/.local/tmp

on:
  push:
    tags:
      - 'stable/**'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version tag'
        required: true

jobs:
  container-image-stable:
    runs-on: ubuntu-latest
    steps:
      - name: Extract version
        run: echo "TAG=$(echo $TAG | cut -d/ -f 2)" >> $GITHUB_ENV
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
            swap-size-mb: 2048
            root-reserve-mb: 12288
            remove-dotnet: 'true'
            remove-android: 'true'
            remove-haskell: 'true'
            remove-codeql: 'true'
            remove-docker-images: 'true'
            build-mount-path: '/home/runner/.local'
      - name: Create tmp directory
        run: mkdir -p $TMPDIR
      - name: apt update
        run: sudo apt update
      - name: Install podman
        run: sudo apt --yes install podman
      - name: Install go-task
        run: |
          curl -L -O https://github.com/go-task/task/releases/download/v3.37.2/task_linux_amd64.deb
          sudo dpkg --install task_linux_amd64.deb
          rm --force task_linux_amd64.deb
      - uses: actions/checkout@v4
      - name: Authenticate to container registry
        run: task container-image:auth
      - name: Build container image
        run: task container-image:build-stable
      - name: Upload container image
        run: task container-image:push
